before:
  hooks:
    - go mod tidy

builds:
  - id: yamlfmt
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

checksum:
  name_template: "checksums.txt"

release:
changelog:
  skip: true
